#!/usr/bin/env python3
"""Re-fetch the self-hosted webfonts and rewrite ../fonts.css.

The Pi may sit on an isolated LAN, so nothing is loaded from a CDN at runtime. Run this
on the workstation (it needs network) and commit the result; the Pi only ever sees the
checked-in .woff2 files.

    python libnodes/static/fonts/regenerate.py
"""

from __future__ import annotations

import pathlib
import re
import urllib.request

HERE = pathlib.Path(__file__).resolve().parent
CSS_OUT = HERE.parent / "fonts.css"

# IBM Plex Sans 400/500/600 + JetBrains Mono 400/500/700, per the design tokens.
GF_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=IBM+Plex+Sans:wght@400;500;600"
    "&family=JetBrains+Mono:wght@400;500;700"
    "&display=swap"
)
UA = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0 Safari/537.36"
)
# The library holds Russian titles, so cyrillic is not optional here.
SUBSETS = {"latin", "latin-ext", "cyrillic"}


def main() -> None:
    req = urllib.request.Request(GF_URL, headers={"User-Agent": UA})
    css = urllib.request.urlopen(req).read().decode()

    faces, downloaded = [], set()
    for subset, block in re.findall(r"/\* ([a-z-]+) \*/\s*(@font-face \{.*?\})", css, re.S):
        if subset not in SUBSETS:
            continue
        family = re.search(r"font-family: '([^']+)'", block).group(1)
        weight = re.search(r"font-weight: (\d+)", block).group(1)
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)

        name = f"{family.lower().replace(' ', '-')}-{weight}-{subset}.woff2"
        if name not in downloaded:
            urllib.request.urlretrieve(url, HERE / name)
            downloaded.add(name)
        faces.append(block.replace(url, f"fonts/{name}"))

    header = "/* Generated by fonts/regenerate.py — do not edit by hand. */\n\n"
    CSS_OUT.write_text(header + "\n\n".join(faces) + "\n")
    print(f"{len(faces)} faces, {len(downloaded)} files -> {CSS_OUT}")


if __name__ == "__main__":
    main()
